# Generated by Django 3.2.13 on 2022-12-25 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
                ('venue', models.CharField(max_length=50)),
                ('attendance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
                ('population', models.IntegerField()),
                ('capital', models.CharField(max_length=50)),
                ('political_climate', models.CharField(max_length=50)),
                ('corruption_level', models.IntegerField()),
                ('fan_loyalty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('referred_name', models.CharField(max_length=50)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=50)),
                ('birth_year', models.IntegerField()),
                ('club', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('political_alignment', models.CharField(max_length=50)),
                ('pc_level', models.IntegerField()),
                ('best_quality', models.CharField(max_length=50)),
                ('worst_quality', models.CharField(max_length=50)),
                ('twitter_followers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('prankster_level', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('aggression', models.IntegerField()),
                ('discipline', models.IntegerField()),
                ('sportsmanship', models.IntegerField()),
                ('wealth', models.IntegerField()),
                ('dad_joke_aptitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonWinner',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('season_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.season')),
                ('team_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.nation')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('action_minute', models.IntegerField()),
                ('game_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game')),
                ('player_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_uid', to='base.nation'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_uid', to='base.nation'),
        ),
        migrations.AddField(
            model_name='game',
            name='season_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.season'),
        ),
    ]
