# Generated by Django 4.1.7 on 2023-06-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('home_team_score', models.IntegerField()),
                ('away_team_score', models.IntegerField()),
                ('venue', models.CharField(max_length=50)),
                ('attendance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('continent', models.CharField(default='', max_length=50)),
                ('population', models.IntegerField()),
                ('capital', models.CharField(default='', max_length=50)),
                ('political_climate', models.CharField(default='', max_length=50)),
                ('corruption_level', models.CharField(default='', max_length=50)),
                ('fan_loyalty', models.CharField(default='', max_length=50)),
                ('faker_locale_options', models.CharField(default='', max_length=50)),
                ('conversion_option', models.CharField(default='', max_length=50)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('referred_name', models.CharField(default='', max_length=50)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=50)),
                ('birth_year', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('political_alignment', models.CharField(max_length=50)),
                ('pc_level', models.IntegerField()),
                ('best_quality', models.CharField(max_length=50)),
                ('worst_quality', models.CharField(max_length=50)),
                ('twitter_followers', models.IntegerField()),
                ('is_manager', models.BooleanField(default=False)),
                ('club', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.club')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.nation')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('prankster_level', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('aggression', models.IntegerField()),
                ('discipline', models.IntegerField()),
                ('sportsmanship', models.IntegerField()),
                ('wealth', models.IntegerField()),
                ('dad_joke_aptitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonWinner',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('season_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.season')),
                ('team_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.nation')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_fee', models.IntegerField()),
                ('transfer_date', models.DateField()),
                ('from_team_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_team_uid', to='base.nation')),
                ('player_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.player')),
                ('to_team_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_team_uid', to='base.nation')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=50)),
                ('action_minute', models.IntegerField()),
                ('game_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.game')),
                ('player_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.player')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.nation')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_uid', to='base.nation'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_uid', to='base.nation'),
        ),
        migrations.AddField(
            model_name='game',
            name='season_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.season'),
        ),
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.league'),
        ),
    ]
