# Generated by Django 4.1.7 on 2023-06-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
