# Generated by Django 4.1.7 on 2023-03-16 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.nation'),
        ),
    ]
