# Generated by Django 4.1.7 on 2023-06-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_nation_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nation',
            old_name='ranking',
            new_name='rank',
        ),
    ]
