# Generated by Django 4.1.7 on 2023-03-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_player_nation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='conversion_option',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='nation',
            name='faker_locale_options',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nation',
            name='capital',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nation',
            name='continent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nation',
            name='corruption_level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nation',
            name='fan_loyalty',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nation',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nation',
            name='political_climate',
            field=models.CharField(default='', max_length=50),
        ),
    ]
