# Generated by Django 4.1.7 on 2023-06-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_player_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='nation',
        ),
    ]
