# Generated by Django 4.1.7 on 2023-03-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_nation_conversion_option_nation_faker_locale_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
