# Generated by Django 4.1.7 on 2023-06-13 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_league_nation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rating',
        ),
    ]
