# Generated by Django 4.1.7 on 2023-06-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_player_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticalReport',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
