version: "3"
services:
  web:
    build: .
    command: bash -c "cd /app/client && npm install && npm run build && cd /app/server && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./client:/app/client
      - ./server:/app/server
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=mysecretkey
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=mydatabaseuser
      - DB_PASSWORD=mypassword
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=mydatabaseuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
