name: Testing
on: push


jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Give permission to run the tests
      run: 
        chmod u+x test

    - name: Give permission to install dependencies
      run:
        chmod u+x build

    - name: Install Dependencies
      run: 
        ./build

    - name: Run The Tests
      run: 
        ./test
