name: Testing
on: push
#
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django Unit Tests
      run: 
        sudo apt-get update -y
        
        sudo apt-get install -y python3-apt

        pip install -r requirements.txt

        python3 manage.py test