name: Testing
on: push
#
jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django Unit Tests
      run: 
        sudo apt-get update -y
        
        sudo apt-get install -y python3-apt

        # give permission to run the script
        chmod u+x build
        ./build

        # give permission to run the script
        chmod u+x test
        ./test